### PR TITLE
Allow multiple ImageId's

### PR DESCRIPTION
**Pull request by Siebrandf**
Added new scriptblock and array rather than string input for the layerid attribute to support for publishing multiple images at once.

### CODE REVIEW

**Comment by ryancbutler** [comment]
Has this been tested with a single imageid?

**Comment by Siebrandf** [comment]
Hey Ryan,

I had it tested succesfully. It also does not alter the original XML block when only one imageid is provided.

Verstuurd vanaf mijn iPhone

Op 25 jun. 2019 om 22:43 heeft Ryan Butler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Has this been tested with a single imageid?

**Comment by ryancbutler** [comment]
👍

**Comment by Siebrandf** [comment]
Perfect! Thx!

**Pull request merged**
