### PR TITLE
Regex Update

### PR DESCRIPTION
**Pull request by bnickerson-fnba**
Hopefully I've done this correctly.

### CODE REVIEW

**Comment by ryancbutler** [comment]
Fantastic!  I'll review this week.

**Comment by ryancbutler** [comment]
#15 
I'm getting an error when trying to use the regex.
```
Exception calling "Match" with "2" argument(s): "parsing "(?<=(]|'))([^'[])(Citrix([^)]+))([^['])(?=([|'))" - Unterminated [] set."
```

**Comment by bnickerson-fnba** [comment]
it looks like there are missing escape ("\") characters in front of the ][ 
This is what mine looks like:

> "(?<=(\]|'))([^'\[]*)\(Citrix([^)]+)\)([^\[']*)(?=(\[|'))"

**Comment by bnickerson-fnba** [comment]
It appears github is removing the backslash escape character?

**Comment by bnickerson-fnba** [comment]
image

**Comment by ryancbutler** [comment]
Ahhh interesting.  Ok, I added the slashes but now doesn't work with the "no-error" output.

**Comment by bnickerson-fnba** [comment]
What do you use to test it? 
image

**Comment by ryancbutler** [comment]
```
(?<=(\]|'))([^'\[]*)\(Citrix([^)]+)\)([^\[']*)(?=(\[|'))
```
Not sure why it isn't working for me.  here is my status

```
The packaging machine [link="https://vcenter01.lab.local/vsphere-client/?csp#extensionId=vsphere.core.vm.summary;context=com.vmware.core.model::ServerObjectRef~6bb77ddb-941d-4124-aa17-eaf579f9742b:VirtualMachine:vm-10349~core"]WIn10ENT1809-2019-01-18_10-04-40.273[/link] has been created. Power on the machine and install the software for the layer. Then, using the Shutdown for Finalize ico
n on the desktop, validate and shutdown the machine so you can finalize the layer.

vSphere Web UI Link = https://vcenter01.lab.local/vsphere-client/?csp#extensionId=vsphere.core.vm.summary;context=com.vmware.core.model::ServerObjectRef~6bb77ddb-941d-4124-aa17-eaf579f9742b:VirtualMachine:vm-10349~core```

**Comment by bnickerson-fnba** [comment]
Yours doesn't have " (Citrix App Layering Packaging Machine)" . The regex matches on "(Citrix" I didn't know you could remove that bit from the machine name.

**Comment by bnickerson-fnba** [comment]
This pattern looks to match your status as well as what I've seen.  
image

**Comment by bnickerson-fnba** [comment]
I updated the regex to the one that works above for both of our use cases.

**Comment by ryancbutler** [comment]
Thanks @MajesticTJ !  Works great!!  Made some minor changes.

**Pull request merged**
