### PR TITLE
 remove-alapplayerrev.ps1

### PR DESCRIPTION
**Pull request by Siebrandf**
reverse engineered removal of an applayer revision. OS and platform layerrev to come

### CODE REVIEW

**Comment by ryancbutler** [comment]
Awesome!  Can you create the same for OS and Platform layers?  Also, can you add some documentation to the README.MD?  Probably can use exactly what you have in the script file.

Note:  Just keep committing to the same branch.  No need to recreate another pull request.  This one will update.

**Comment by Siebrandf** [comment]
will do!

**Comment by ryancbutler** [comment]
Adds #13

**Review by Siebrandf — COMMENTED** [review]
some minor textual changes to the remove-applayerrev, remove-oslayerrev and remove-platformlayerrev are tested and added

**Pull request merged**
