### PR TITLE
 Update Set-ALImage to include single app update

### PR DESCRIPTION
**Pull request by Siebrandf**

### CODE REVIEW

**Comment by ryancbutler** [comment]
So this adds a new app layer to an image?  What does it do to the existing layers or one that is the same name?

**Comment by Siebrandf** [comment]
Hey Ryan,

It updates an existing app layer based on the Layerid for the layer, and revision id for the revision within that Layer. When you do not provide these parameters or the values are blank or $null, it leaves the app assignments untouched.
Other than that it behalve just like it was.

With this in place you can automate updating an image with the latest revision for a given app Layer, based on the id’s. Just like it does for an os Layer of platform layer.

I use this to update a cloned image for non-persist VDI with a new os Layer and Office Layer revision including the monthly wsus patches

Verstuurd vanaf mijn iPad

Op 19 apr. 2019 om 19:32 heeft Ryan Butler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


So this adds a new app layer to an image? What does it do to the existing layers or one that is the same name?

**Comment by ryancbutler** [comment]
Makes sense!  Pretty cool!

**Comment by Siebrandf** [comment]
Thx!

Verstuurd vanaf mijn iPhone

Op 19 apr. 2019 om 22:57 heeft Ryan Butler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Makes sense! Pretty cool!

**Pull request merged**
